name: Gussur Auto Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Jalan tiap jam 07:00 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Bagian ini penting untuk memberi tahu GitHub agar menyiapkan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gussur Scraper
        env:
          WP_USER: ${{ secrets.WP_USER_GUSSUR }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASS_GUSSUR }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main_gussur.py
